Add section on which filters are being run to the output files section of pVACseq, pVACbind, and pVACfuse
griffithlab/pVACtools pull request #598
Opened 2020-10-13 15:58 UTC by susannasiebert

Closes #556

2020-10-19 21:40 UTC, malachig commented on docs/pvacbind/output_files.rst
> +filter commends may be useful to reproduce the filtering or to chose different
commends -> commands

2020-10-19 21:42 UTC, malachig commented on docs/pvacfuse/output_files.rst
> +filter commends may be useful to reproduce the filtering or to chose different
commends -> commands

2020-10-19 21:42 UTC, malachig commented on docs/pvacseq/output_files.rst
> +filter commends may be useful to reproduce the filtering or to chose different
commends -> commands

2020-10-19 21:43 UTC, malachig requested changes
This is clear and concise.  Makes sense to me.  Just a couple minor typos noted.

2020-10-20 15:08 UTC, susannasiebert commented on docs/pvacbind/output_files.rst
> +filter commends may be useful to reproduce the filtering or to chose different
```suggestion
filter commands may be useful to reproduce the filtering or to chose different
```

2020-10-20 15:08 UTC, susannasiebert commented on docs/pvacfuse/output_files.rst
> +filter commends may be useful to reproduce the filtering or to chose different
```suggestion
filter commands may be useful to reproduce the filtering or to chose different
```

2020-10-20 15:08 UTC, susannasiebert commented on docs/pvacseq/output_files.rst
> +filter commends may be useful to reproduce the filtering or to chose different
```suggestion
filter commands may be useful to reproduce the filtering or to chose different
```

2020-10-20 16:21 UTC, malachig approved these changes

2021-01-15 15:37 UTC, merged